%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/carinasauter/Google Drive/Spatial Data and Analysis/final_project/film_locations.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/11/26 11:40:29

%% Initialize variables.
filename = '/Users/carinasauter/Google Drive/Fall 2016/Spatial Data and Analysis/final_project/film_locations.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: text (%q)
%	column2: double (%f)
%   column3: text (%q)
%	column4: text (%q)
%   column5: text (%q)
%	column6: text (%q)
%   column7: text (%q)
%	column8: text (%q)
%   column9: text (%q)
%	column10: text (%q)
%   column11: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%f%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
filmlocations = table(dataArray{1:end-1}, 'VariableNames', {'Title','ReleaseYear','Locations','FunFacts','ProductionCompany','Distributor','Director','Writer','Actor1','Actor2','Actor3'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;